unixorn/jpb.zshplugin

- bin/local-ip-address
I found that since I had bridges defined with a default route that this command didn't work for me.   plus the grep call was just bugging me since it's unnecessary when you call ifconfig with 'inet' as the address family.
> filter for inet4 before awking

- README.md
- bin/title-text
Add script to set the title in apps that respect VT100 escape codes
> Add title-text

- jpb.plugin.zsh
I believe that gitlgg should alias something like `git log`and not just `log`
- [x ] Bug fix (non-breaking change which fixes an issue)
> add a missing `git` to gitlgg alias

- PULL_REQUEST_TEMPLATE.md
- jpb.plugin.zsh
* Add `repair-zsh-history` function
> Add repair-zsh-history function

- bin/newscript
Fix 
Fix typo in `def main` in python template
> Fix dumb typo in newscript

- README.md
* Update oh-my-zsh links to point to new location on Github.
* Update zgen references to zgenom since zgenom is getting actively maintained.
> Fix ohmyzsh link

- bin/newscript
Make log output nicer in python scripts generated by `newscript`
Add time to log output
> Include timestamp in log output by default

- bin/newscript
- bin/repair-zsh-history
- jpb.plugin.zsh
Convert `repair-zsh-history` from a function to a standalone script for robustness.
> Add history repair script

- jpb.plugin.zsh
My configuration is to run against my local working copy of the plugin instead of tip of master. Realized after setting up a new laptop that I never committed this change, oops!
- Fix `hgrep` and `hgrep 40` handling of multiword arguments.
> Fix hgrep and hgrep40 behavior with multiword arguments

- jpb.plugin.zsh
Got tired of running `dmesg` and getting an error because I forgot to `sudo` it.
Added `alias dmesg='sudo dmesg'` to plugin
> Add alias for dmesg

- bin/newscript
I got tired of adding `fail` by hand, made it a default
Adds `fail` function to generated shell scripts that writes a message to stderr and then exits non-zero.
> Add fail function to bash scripts generated by newscript

- README.md
- bin/newscript
shell scripts generated by `newscript` have an error now that I've added a `fail()` function.
Forgot to escape the `\n` in `newscript`'s internal bash template.
> Fix printf bug in newscript

- .github/PULL_REQUEST_TEMPLATE.md
Clean up markdown formatting in PR template
n/a
> Clean up markdown formatting in PR template

- bin/newscript
I end up adding a debug function to most bash scripts anyway, so add it to the template.
- Add `debug()` function to bash template in `newscript`
- rubocop cleanups in `newscript`
> Add debug() to bash scripts created by newscript

- jpb.plugin.zsh
TRAPINT handling is borged by zsh-quickstart-kit in https://github.com/unixorn/zsh-quickstart-kit/pull/117
Merge this after that.
> Move trapint handling to zsh quickstart kit

- bin/newscript
We don't always need scratch directories in new scripts.
Keep the scratchdir functions together so they're easier to remove when not needed by a new script.
> Make it easier to remove the scratchdir helpers in newscript

- README.md
- bin/human-time
`human-time` converts integer numbers of seconds into more human-intuitive form.
`human-time 88000` will print `1d 26m 40s`, for example.
> Add human-time helper script

- README.md
- bin/$
- jpb.plugin.zsh
Lots of command examples (especially heroku) lead command docs with `$` which make it kind of annoying to copy/paste, especially when there's multiple commands to copy.
Add `$` script so that when you're pasting a command example with a leading `$` it will just work.
> Add `$` script

- .github/workflows/superlinter.yml
- README.md
- bin/jira
Make it easy to open an existing jira ticket from the command line.
Add `jira` helper script
> Add a jira helper script

- README.md
- bin/lineprof
Add `lineprof`. Annotates each line of input with the number of milliseconds elapsed since the last line. Useful for figuring out slow points of output-producing programs.
> Add `lineprof`

- README.md
- bin/ls-open-ports
- bin/ls-sockets
- bin/ls-tcp-sockets
- bin/ls-udp-sockets
- jpb.plugin.zsh
I can never remember the right args to `lsof`, so add some helper scripts.
- Add `ls-sockets`
- Add `ls-tcp-sockets`
- Add `ls-udp-sockets`
> Add more `lsof` helpers

- README.md
- bin/lineprof
`clean-clipboard` was moved to tumult plugin, remove it from README.md
> Remove `clean-clipboard` from readme

- jpb.plugin.zsh
Use `$*` instead of `$@` in `hgrep` and `hgrep40`
> Finally commit the `hgrep` fixes

- jpb.plugin.zsh
- Alias `open` to `xdg-open` when running on linux and it is found in `$PATH`
- Add `on_macos` function
> Add alias for `open` when running on linux

- bin/newscript
Scripts generated by `newscript` had ugly indentation mismatches.
Fix indentation in generated bash scripts
> Fix indentation in bash scripts generated by `newscript`

- jpb.plugin.zsh
We inevitably end up wanting to delete a history entry, `delete-from-zsh-history` makes that easier.
Add `delete-from-zsh-history` function
> Add `delete-from-zsh-history` function

- jpb.plugin.zsh
I don't want to have to remember the names or syntax of the linux equivalents for `pbpaste` and `pbcopy` when I'm in on a linux machine.
When running on linux, if there's an `xclip` command, add `pbpaste` and `pbcopy` helper scripts.
> Add `pbpaste` and `pbcopy` helpers on linux

- bin/newscript
Add a `echo-stderr` helper function to the default `bash` template
> Add `echo-stderr` helper to the default `bash` template

- bin/750
- bin/dns-resolvers
- bin/newscript
Naturally macOS makes figuring out what DNS servers your machine is using more complicated than `cat /etc/resolv.conf`.
I can never remember the right `scutil` command, so adding this helper script.
- Add `dns-resolvers` script
> Add `dns-resolvers` script

- README.md
- bin/clean-whiteboard-picture
- bin/nanotime
- bin/time-in-ms
- jpb.plugin.zsh
Sometimes I need very granular timing 
- Add `nanotime` command that reports execution time in milliseconds
> Add `nanotime` script

- README.md
- bin/gtouch
- jpb.plugin.zsh
- Add a quick way to make the prompt boring for screen shots
- Use more idiomatic `zsh` for updating the user's `$PATH`
> Add `boring-prompt()`

- README.md
- bin/newscript
- bin/ssh-remove-known-host
I can never remember the command to remove a host, and since the format update, you can't just edit `~/.ssh/known_hosts` and search for the IP/hostname.
Not sure why they switched to a new format that's more pain in the ass.
> Add `ssh-remove-known-host` script

- jpb.plugin.zsh
fixes #95
the GREP_COLOR setting is deprecated in GNU grep >= 3.8 and spits deprecation errors
* Added a function to compare two strings that contain versions
* used it to compare against 3.8 (and GNU)
* sets GREP_COLOR(S) accordingly
works fine here locally
> fix: set GREP_COLORS correctly for GNU grep >= 3.8

- .github/workflows/mega-linter.yml
KICS flags things as errors that should really only be warnings
Updated mega-linter configuration to treat KICS errors as warnings
> Demote KICS errors to warnings

- README.md
- bin/pydoc
Add `pydoc` script to search for something on docs.python.org and open the results in your default browser.
> Add `pydoc` helper

- jpb.plugin.zsh
only set bat alias when the binary is present
> only set bat alias when the binary is present

- bin/newscript
Bash templates generated by `newscript` had places that `shellcheck` complained about.
I don't need a complaint that `$foo` isn't in `"` when it's something like `aa="$(foo bar $baz)"
- Add shellcheck disables for some functions
- Improve inline examples
Been using it on my personal laptop and am finally getting around to merging the changes.
> Minor tweaks to newscript

- .github/workflows/awesomebot.yml
> Some 4XX errors trigger false negatives
