README.md
bin/change-extension

Simple script to change *.foo to *.bar

Add change-extension script

---

README.md
bin/dumpdns

It is occasionally convenient to dump all the entries in a domain, but I do it rarely enough I need to look up how to make `nslookup` do that, so adding a wrapper script for it.

Add dumpdns script

---

bin/pushover

Add pushover script

---

README.md
bin/dedupe-in-order

Add `dedupe-in-order` script - this is a RAM pig on large files

Add `dedupe-in-order` script

---

README.md
bin/snag-dl

Add snag-dl script

---

README.md
bin/600
bin/700
bin/755
bin/block-until-internet
bin/clean-whiteboard-picture
bin/datestamp
bin/google
bin/html2markdown
bin/ipaddresses
bin/local-ip-address
bin/local-ipv6-address
bin/lsof-unlinked
bin/markdown-open
bin/mtr-url
bin/murder
bin/osx-get-wifi-password
bin/random-password
bin/randsleep
bin/read-windows-key-from-bios
bin/relocate-virtualenv
bin/retry
bin/rpmburst
bin/running
bin/seq
bin/shovel-gpg-keys
bin/snag-dl
bin/tableflip
bin/what.py
jpb.plugin.zsh

Make this more usable by non-ZSH users
* Remove `mtr_url` function from plugin, add `mtr-url` to bindir to replace it
* Refactor file permissions helpers into bin scripts and remove shell functions
* Update shebangs to use `/usr/bin/env` to find interpreters
* Add execs to wrappers so they return the underlying exit codes

Refactor plugin file

---

PULL_REQUEST_TEMPLATE.md
README.md
bin/fix-zsh-history
bin/newscript

* Add `fix-zsh-history` to fix a corrupt ZSH history file
* Update `newscript`
* Fix typo in PR template

Add script to fix a corrupt ZSH history file

---

bin/newscript

Include file name, line number and function names in log output

Improve default logging in newescript py scripts

---

.github/PULL_REQUEST_TEMPLATE.md
bin/newscript

* Make logging output include log level
* Update PR template

Make logging output include log level

---

README.md
bin/http-debug
bin/http-headers

Add http-headers and http-debug scripts

Add http-headers and http-debug scripts

---

README.md

Remove link to Ryan's dotfiles since the repo has been removed

Ryan took his dotfiles repo offline

---

.github/workflows/awesomebot.yml
.travis.yml
README.md

Want to switch from depending on travis. We're hosted on GitHub, so if they're broken, we're broken anyway.
Remove travis config, run markdown check from a Github action.

Switch to github action from travis

---

bin/csr-decode
bin/decode-cert
bin/p7b-decode
jpb.plugin.zsh

Refactor SSL functions into scripts

Refactor out some SSL tools

---

jpb.plugin.zsh

From Jordan Sissel's dotfiles:
Lots of command examples (especially heroku) lead command docs with '$' which
make it annoying to copy/paste, especially when there's multiple commands to copy.
This hacks around the problem by making a '$' command that simply runs
whatever arguments are passed to it. So you can copy commands easily.

Add a `$` function

---

bin/newscript

Forgot to commit change to run `cleanup` at exit.

Update bash script template in newscript

---

README.md

Put status and description ahead of TOC

---

jpb.plugin.zsh

Add some aliases for VSCode

---

jpb.plugin.zsh

From https://github.com/jessfraz/dotfiles/blob/master/.functions
Go to a folder easily in your gopath

Add jfrazelle's gogo function

---

.github/workflows/superlinter.yml
README.md
bin/find-in-files

- Add `find-in-files` script that combines `ripgrep` and `fzf`
- Update `superlinter` configuration

Add find-in-files script

---

bin/local-ip-address
bin/local-ipv4-address

Somehow I never committed this bugfix

Fix bug in local-ip-address script

---

bin/newscript

Add `has()` function to newscript-generated bash scripts

Add has function to newscript-generated bash scripts

---

README.md
bin/plot

Add terminal plot tools

---

README.md
bin/wtfis

`wtfis` looks up its argument on cheat.sh. It uses your default browser on macOS and `curl` on any other OS.

Add wtfis script

---

README.md
bin/name-tab
bin/name-window

Add name-window helper script

---

.github/workflows/superlinter.yml

Renamed `master` branch to `main`, update `superlinter` configuration.
Update `superlinter` to use `main` branch

Update superlinter to use main branch

---

.github/workflows/superlinter.yml

Update superlinter configuration to v4

Update superlinter configuration to v4

---

README.md

Forgot to update the badge when I renamed the default branch to `main`.

Fix the status badge now that we've moved to main

---

bin/find-in-files

Confirm `rg` is in `$PATH` before trying to use it

Add rg check to `find-in-files`

---

README.md
bin/datauri
bin/exiftool
bin/http-reflect
bin/port-listeners-ipv4
bin/port-listeners-ipv6
bin/strip-ansi-codes

Publish some more stuff I've been using
- Clean up `http-reflect.py` with `black` and rename to `http-reflect` - we don't need no stinking file extensions
- Add `exiftool` script
- Add `datauri` script
- Add `port-listeners-ipv{4,6}`
- Add `strip-ansi-codes` script

Script cleanups

---

.github/workflows/awesomebot.yml
.github/workflows/mega-linter.yml
README.md

Maintenance
- Switch from superlinter to mega-linter
- Update awesomebot 
- Ignore 5?? errors so we don't have a false failure on PRs if a web server is overloaded.
- Add 1 second delay between link checks to prevent us getting rate-limited

Gh actions updates

---

README.md
bin/ascii-bar

Add `ascii-bar` script

---

README.md
bin/ansi2html
bin/ascii-bar
bin/block-until-internet
bin/clean-whiteboard-picture
bin/datauri
bin/datestamp
bin/diff-summary
bin/fix-zsh-history
bin/headers
bin/html2markdown
bin/http-reflect
bin/iflip
bin/memcached-tool
bin/memcached-top
bin/what.py
bin/yesterday

Clean things up
- Make credits consistent in scripts
- Update some shebangs to use `/usr/bin/env`
- Minor text tweaks

Update credits in readme

---

README.md
bin/human-path

Add `human-path` script

---

README.md
bin/middle

Add `middle` script from commandline-fu

Add `middle` script

---

README.md
bin/json-to-yaml
bin/json2yaml
bin/yaml-to-json
bin/yaml2json

Found myself doing this just often enough to want a helper script.
Add `yaml-to-json` and `json-to-yaml` scripts

Add yaml-to-json

---

README.md
bin/urldecode
bin/urlencode

Add `urldecode` and `urlencode` tool scripts.

Add `urldecode` and `urlencode`

---

jpb.plugin.zsh

Move alias out of `~/.zshrc.d` and into the plugin proper

Add `snake_case` alias

---

.github/dependabot.yml
jpb.plugin.zsh

Add aliases & a dependabot configuration

Add aliases & a dependabot configuration

---

jpb.plugin.zsh

- Add more typo helpers
- Add `ssh-force-password` and `ssh-force-password-no-hostcheck`
- Add guardrails around adding `pbcopy` and `pbpaste` functions on non-macOS

Alias and function updates

---

.github/workflows/mega-linter.yml
README.md
bin/bindiff
bin/hex-to-bin
bin/is-remote-session
bin/newscript
bin/remote-packet-capture
bin/ssl-cert-check
jpb.plugin.zsh

Sync recent additions to github
- Add `bindiff`
- Add `hex-to-string`
- Add `is-remote-session`
- Add `remote-packet-capture`
- Add `ssh-copy-key`
- Add `check-ssl-cert`

Add a bunch of helper scripts

---

bin/newscript

- Add `approve`, `my-name` and `usage`
- Silence bad shellcheck warnings
- Explicitly MIT license generated scripts to make them easier to use

Update `newscript`-generated scripts

---

README.md
bin/openports

This has been floating around as a function in my local `~/.zshrc.d` for a while.
Wraps `ss` and makes a prettier list of open ports

Add `openports`

---

bin/remote-shark

Add helper to run wireshark on a remote host

Add helper to run wireshark on a remote host

---

.github/workflows/mega-linter.yml
README.md
bin/explainshell
bin/mfs-instatrash
bin/newscript
jpb.plugin.zsh

- Add some utility functions from @ag4ve's dotfiles
- Add a `path-exists` function to bash script template in `newscript`
- Add `mfs-instatrash` helper script to set the trash expiry time of a file or directory to 0 on a mfs file system
- Add `explainshell` to explain a shell command using explainshell.com

Add more utility functions

---

jpb.plugin.zsh

Add ANSI color variables

---

bin/openports
bin/p7b-decode
bin/pidpwd
bin/randsleep

Housekeeping

---

README.md

Minor wording updates
